//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XEmuera.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigsText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigsText() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XEmuera.Resources.ConfigsText", typeof(ConfigsText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 自适应文字与图像 的本地化字符串。
        /// </summary>
        internal static string AdaptiveFont {
            get {
                return ResourceManager.GetString("AdaptiveFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自适应文字与图像大小 的本地化字符串。
        /// </summary>
        internal static string AdaptiveFontSize {
            get {
                return ResourceManager.GetString("AdaptiveFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许重写系统函数 的本地化字符串。
        /// </summary>
        internal static string AllowFunctionOverloading {
            get {
                return ResourceManager.GetString("AllowFunctionOverloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string AllowLongInputByMouse {
            get {
                return ResourceManager.GetString("AllowLongInputByMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许多重启动 的本地化字符串。
        /// </summary>
        internal static string AllowMultipleInstances {
            get {
                return ResourceManager.GetString("AllowMultipleInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动保存进度 的本地化字符串。
        /// </summary>
        internal static string AutoSave {
            get {
                return ResourceManager.GetString("AutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背景色 的本地化字符串。
        /// </summary>
        internal static string BackColor {
            get {
                return ResourceManager.GetString("BackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BAR文字1 的本地化字符串。
        /// </summary>
        internal static string BarChar1 {
            get {
                return ResourceManager.GetString("BarChar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BAR文字2 的本地化字符串。
        /// </summary>
        internal static string BarChar2 {
            get {
                return ResourceManager.GetString("BarChar2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不对按钮行折返换行 的本地化字符串。
        /// </summary>
        internal static string ButtonWrap {
            get {
                return ResourceManager.GetString("ButtonWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug模式下变更MASTER的称呼 的本地化字符串。
        /// </summary>
        internal static string ChangeMasterNameIfDebug {
            get {
                return ResourceManager.GetString("ChangeMasterNameIfDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 COM_ABLE初期値 的本地化字符串。
        /// </summary>
        internal static string ComAbleDefault {
            get {
                return ResourceManager.GetString("ComAbleDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许CALL调用事件函数 的本地化字符串。
        /// </summary>
        internal static string CompatiCallEvent {
            get {
                return ResourceManager.GetString("CompatiCallEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CALLNAME为空时用NAME代替 的本地化字符串。
        /// </summary>
        internal static string CompatiCALLNAME {
            get {
                return ResourceManager.GetString("CompatiCALLNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DRAWLINE始终打印在新行 的本地化字符串。
        /// </summary>
        internal static string CompatiDRAWLINE {
            get {
                return ResourceManager.GetString("CompatiDRAWLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强制执行无法解析的行 的本地化字符串。
        /// </summary>
        internal static string CompatiErrorLine {
            get {
                return ResourceManager.GetString("CompatiErrorLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户函数自动补全TOSTR 的本地化字符串。
        /// </summary>
        internal static string CompatiFuncArgAutoConvert {
            get {
                return ResourceManager.GetString("CompatiFuncArgAutoConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户函数允许省略全部参数 的本地化字符串。
        /// </summary>
        internal static string CompatiFuncArgOptional {
            get {
                return ResourceManager.GetString("CompatiFuncArgOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 函数、属性的大小写敏感 的本地化字符串。
        /// </summary>
        internal static string CompatiFunctionNoignoreCase {
            get {
                return ResourceManager.GetString("CompatiFunctionNoignoreCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重现ver1739前的非按钮折返 的本地化字符串。
        /// </summary>
        internal static string CompatiLinefeedAs1739 {
            get {
                return ResourceManager.GetString("CompatiLinefeedAs1739", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用eramaker规范的伪变量RAND 的本地化字符串。
        /// </summary>
        internal static string CompatiRAND {
            get {
                return ResourceManager.GetString("CompatiRAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用SP角色 的本地化字符串。
        /// </summary>
        internal static string CompatiSPChara {
            get {
                return ResourceManager.GetString("CompatiSPChara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定调试窗口的位置 的本地化字符串。
        /// </summary>
        internal static string DebugSetWindowPos {
            get {
                return ResourceManager.GetString("DebugSetWindowPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动时显示调试窗口 的本地化字符串。
        /// </summary>
        internal static string DebugShowWindow {
            get {
                return ResourceManager.GetString("DebugShowWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调试窗口高度 的本地化字符串。
        /// </summary>
        internal static string DebugWindowHeight {
            get {
                return ResourceManager.GetString("DebugWindowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调试窗口X坐标 的本地化字符串。
        /// </summary>
        internal static string DebugWindowPosX {
            get {
                return ResourceManager.GetString("DebugWindowPosX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调试窗口Y坐标 的本地化字符串。
        /// </summary>
        internal static string DebugWindowPosY {
            get {
                return ResourceManager.GetString("DebugWindowPosY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动时窗口前置化显示 的本地化字符串。
        /// </summary>
        internal static string DebugWindowTopMost {
            get {
                return ResourceManager.GetString("DebugWindowTopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调试窗口宽度 的本地化字符串。
        /// </summary>
        internal static string DebugWindowWidth {
            get {
                return ResourceManager.GetString("DebugWindowWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载时显示报告 的本地化字符串。
        /// </summary>
        internal static string DisplayReport {
            get {
                return ResourceManager.GetString("DisplayReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最低显示警告等级 的本地化字符串。
        /// </summary>
        internal static string DisplayWarningLevel {
            get {
                return ResourceManager.GetString("DisplayWarningLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DRAWLINE文字 的本地化字符串。
        /// </summary>
        internal static string DrawLineString {
            get {
                return ResourceManager.GetString("DrawLineString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑器运行参数 的本地化字符串。
        /// </summary>
        internal static string EditorArgument {
            get {
                return ResourceManager.GetString("EditorArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string EditorType {
            get {
                return ResourceManager.GetString("EditorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EXPLVの初期値 的本地化字符串。
        /// </summary>
        internal static string ExpLvDef {
            get {
                return ResourceManager.GetString("ExpLvDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选中文字色 的本地化字符串。
        /// </summary>
        internal static string FocusColor {
            get {
                return ResourceManager.GetString("FocusColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体名称 的本地化字符串。
        /// </summary>
        internal static string FontName {
            get {
                return ResourceManager.GetString("FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文字与图像缩放倍数 的本地化字符串。
        /// </summary>
        internal static string FontScale {
            get {
                return ResourceManager.GetString("FontScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体大小 的本地化字符串。
        /// </summary>
        internal static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ForbidOneCodeVariable {
            get {
                return ResourceManager.GetString("ForbidOneCodeVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文字色 的本地化字符串。
        /// </summary>
        internal static string ForeColor {
            get {
                return ResourceManager.GetString("ForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每秒帧数 的本地化字符串。
        /// </summary>
        internal static string FPS {
            get {
                return ResourceManager.GetString("FPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 函数未被调用时的警告处理 的本地化字符串。
        /// </summary>
        internal static string FunctionNotCalledWarning {
            get {
                return ResourceManager.GetString("FunctionNotCalledWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 函数未找到时的警告处理 的本地化字符串。
        /// </summary>
        internal static string FunctionNotFoundWarning {
            get {
                return ResourceManager.GetString("FunctionNotFoundWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忽视大小写 的本地化字符串。
        /// </summary>
        internal static string IgnoreCase {
            get {
                return ResourceManager.GetString("IgnoreCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忽略未被调用过的函数 的本地化字符串。
        /// </summary>
        internal static string IgnoreUncalledFunction {
            get {
                return ResourceManager.GetString("IgnoreUncalledFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string IgnoreWarningFiles {
            get {
                return ResourceManager.GetString("IgnoreWarningFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 死循环超时警告（毫秒） 的本地化字符串。
        /// </summary>
        internal static string InfiniteLoopAlertTime {
            get {
                return ResourceManager.GetString("InfiniteLoopAlertTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后更新口令 的本地化字符串。
        /// </summary>
        internal static string LastKey {
            get {
                return ResourceManager.GetString("LastKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每行高度 的本地化字符串。
        /// </summary>
        internal static string LineHeight {
            get {
                return ResourceManager.GetString("LineHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起動時簡略表示 的本地化字符串。
        /// </summary>
        internal static string LoadLabel {
            get {
                return ResourceManager.GetString("LoadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 历史记录文字色 的本地化字符串。
        /// </summary>
        internal static string LogColor {
            get {
                return ResourceManager.GetString("LogColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 长按屏幕跳过文本 的本地化字符串。
        /// </summary>
        internal static string LongPressSkip {
            get {
                return ResourceManager.GetString("LongPressSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 长按所需毫秒数 的本地化字符串。
        /// </summary>
        internal static string LongPressSkipTime {
            get {
                return ResourceManager.GetString("LongPressSkipTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录日志的行数 的本地化字符串。
        /// </summary>
        internal static string MaxLog {
            get {
                return ResourceManager.GetString("MaxLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 販売アイテム数 的本地化字符串。
        /// </summary>
        internal static string MaxShopItem {
            get {
                return ResourceManager.GetString("MaxShopItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 単位の位置 的本地化字符串。
        /// </summary>
        internal static string MoneyFirst {
            get {
                return ResourceManager.GetString("MoneyFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 お金の単位 的本地化字符串。
        /// </summary>
        internal static string MoneyLabel {
            get {
                return ResourceManager.GetString("MoneyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PALAMLVの初期値 的本地化字符串。
        /// </summary>
        internal static string PalamLvDef {
            get {
                return ResourceManager.GetString("PalamLvDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 横向平移速度 的本地化字符串。
        /// </summary>
        internal static string PanSpeed {
            get {
                return ResourceManager.GetString("PanSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PBANDの初期値 的本地化字符串。
        /// </summary>
        internal static string pbandDef {
            get {
                return ResourceManager.GetString("pbandDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PRINTC最大数量 的本地化字符串。
        /// </summary>
        internal static string PrintCLength {
            get {
                return ResourceManager.GetString("PrintCLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PRINTC并列数量 的本地化字符串。
        /// </summary>
        internal static string PrintCPerLine {
            get {
                return ResourceManager.GetString("PrintCPerLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮显示列数 的本地化字符串。
        /// </summary>
        internal static string QuickButtonColumn {
            get {
                return ResourceManager.GetString("QuickButtonColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮字体大小 的本地化字符串。
        /// </summary>
        internal static string QuickButtonFontSize {
            get {
                return ResourceManager.GetString("QuickButtonFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮间隔 的本地化字符串。
        /// </summary>
        internal static string QuickButtonSpacing {
            get {
                return ResourceManager.GetString("QuickButtonSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮长度 的本地化字符串。
        /// </summary>
        internal static string QuickButtonWidth {
            get {
                return ResourceManager.GetString("QuickButtonWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载时解析参数 的本地化字符串。
        /// </summary>
        internal static string ReduceArgumentOnLoad {
            get {
                return ResourceManager.GetString("ReduceArgumentOnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ReduceFormattedStringOnLoad {
            get {
                return ResourceManager.GetString("ReduceFormattedStringOnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RELATIONの初期値 的本地化字符串。
        /// </summary>
        internal static string RelationDef {
            get {
                return ResourceManager.GetString("RelationDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用存档数量 的本地化字符串。
        /// </summary>
        internal static string SaveDataNos {
            get {
                return ResourceManager.GetString("SaveDataNos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 滚动行数 的本地化字符串。
        /// </summary>
        internal static string ScrollHeight {
            get {
                return ResourceManager.GetString("ScrollHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检索子目录 的本地化字符串。
        /// </summary>
        internal static string SearchSubdirectory {
            get {
                return ResourceManager.GetString("SearchSubdirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动时固定窗口位置 的本地化字符串。
        /// </summary>
        internal static string SetWindowPos {
            get {
                return ResourceManager.GetString("SetWindowPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像抗锯齿 的本地化字符串。
        /// </summary>
        internal static string ShapeAntialias {
            get {
                return ResourceManager.GetString("ShapeAntialias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像过滤质量 的本地化字符串。
        /// </summary>
        internal static string ShapeFilterQuality {
            get {
                return ResourceManager.GetString("ShapeFilterQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许调整窗口宽度 的本地化字符串。
        /// </summary>
        internal static string SizableWindow {
            get {
                return ResourceManager.GetString("SizableWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大跳过帧数 的本地化字符串。
        /// </summary>
        internal static string SkipFrame {
            get {
                return ResourceManager.GetString("SkipFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按文件名顺序读取 的本地化字符串。
        /// </summary>
        internal static string SortWithFilename {
            get {
                return ResourceManager.GetString("SortWithFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 汚れの初期値 的本地化字符串。
        /// </summary>
        internal static string StainDefault {
            get {
                return ResourceManager.GetString("StainDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用全角空格填充空白区域 的本地化字符串。
        /// </summary>
        internal static string SystemAllowFullSpace {
            get {
                return ResourceManager.GetString("SystemAllowFullSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string SystemIgnoreStringSet {
            get {
                return ResourceManager.GetString("SystemIgnoreStringSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 展开FORM中的三连记号 的本地化字符串。
        /// </summary>
        internal static string SystemIgnoreTripleSymbol {
            get {
                return ResourceManager.GetString("SystemIgnoreTripleSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用角色变量的参数自动补全 的本地化字符串。
        /// </summary>
        internal static string SystemNoTarget {
            get {
                return ResourceManager.GetString("SystemNoTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将存档保存为二进制格式 的本地化字符串。
        /// </summary>
        internal static string SystemSaveInBinary {
            get {
                return ResourceManager.GetString("SystemSaveInBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以UTF-8编码保存文件 的本地化字符串。
        /// </summary>
        internal static string SystemSaveInUTF8 {
            get {
                return ResourceManager.GetString("SystemSaveInUTF8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文字抗锯齿 的本地化字符串。
        /// </summary>
        internal static string TextAntialias {
            get {
                return ResourceManager.GetString("TextAntialias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绘图接口 的本地化字符串。
        /// </summary>
        internal static string TextDrawingMode {
            get {
                return ResourceManager.GetString("TextDrawingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关联文本编辑器 的本地化字符串。
        /// </summary>
        internal static string TextEditor {
            get {
                return ResourceManager.GetString("TextEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文字过滤质量 的本地化字符串。
        /// </summary>
        internal static string TextFilterQuality {
            get {
                return ResourceManager.GetString("TextFilterQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用eramaker规范的TIMES计算 的本地化字符串。
        /// </summary>
        internal static string TimesNotRigorousCalculation {
            get {
                return ResourceManager.GetString("TimesNotRigorousCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 時間切れ表示 的本地化字符串。
        /// </summary>
        internal static string TimeupLabel {
            get {
                return ResourceManager.GetString("TimeupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 システムメニュー0 的本地化字符串。
        /// </summary>
        internal static string TitleMenuString0 {
            get {
                return ResourceManager.GetString("TitleMenuString0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 システムメニュー1 的本地化字符串。
        /// </summary>
        internal static string TitleMenuString1 {
            get {
                return ResourceManager.GetString("TitleMenuString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用调试指令 的本地化字符串。
        /// </summary>
        internal static string UseDebugCommand {
            get {
                return ResourceManager.GetString("UseDebugCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用图像缓冲 的本地化字符串。
        /// </summary>
        internal static string UseImageBuffer {
            get {
                return ResourceManager.GetString("UseImageBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用键盘宏 的本地化字符串。
        /// </summary>
        internal static string UseKeyMacro {
            get {
                return ResourceManager.GetString("UseKeyMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内部使用的汉字编码 的本地化字符串。
        /// </summary>
        internal static string useLanguage {
            get {
                return ResourceManager.GetString("useLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示菜单栏 的本地化字符串。
        /// </summary>
        internal static string UseMenu {
            get {
                return ResourceManager.GetString("UseMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用鼠标 的本地化字符串。
        /// </summary>
        internal static string UseMouse {
            get {
                return ResourceManager.GetString("UseMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用_Rename.csv 的本地化字符串。
        /// </summary>
        internal static string UseRenameFile {
            get {
                return ResourceManager.GetString("UseRenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用_Replace.csv 的本地化字符串。
        /// </summary>
        internal static string UseReplaceFile {
            get {
                return ResourceManager.GetString("UseReplaceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在sav文件夹中创建存档 的本地化字符串。
        /// </summary>
        internal static string UseSaveFolder {
            get {
                return ResourceManager.GetString("UseSaveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示eramaker兼容性相关警告 的本地化字符串。
        /// </summary>
        internal static string WarnBackCompatibility {
            get {
                return ResourceManager.GetString("WarnBackCompatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重写系统函数时显示警告 的本地化字符串。
        /// </summary>
        internal static string WarnFunctionOverloading {
            get {
                return ResourceManager.GetString("WarnFunctionOverloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重复定义非事件函数时显示警告 的本地化字符串。
        /// </summary>
        internal static string WarnNormalFunctionOverloading {
            get {
                return ResourceManager.GetString("WarnNormalFunctionOverloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动时将窗口最大化 的本地化字符串。
        /// </summary>
        internal static string WindowMaximixed {
            get {
                return ResourceManager.GetString("WindowMaximixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口X坐标 的本地化字符串。
        /// </summary>
        internal static string WindowPosX {
            get {
                return ResourceManager.GetString("WindowPosX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口Y坐标 的本地化字符串。
        /// </summary>
        internal static string WindowPosY {
            get {
                return ResourceManager.GetString("WindowPosY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口宽度 的本地化字符串。
        /// </summary>
        internal static string WindowX {
            get {
                return ResourceManager.GetString("WindowX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口高度 的本地化字符串。
        /// </summary>
        internal static string WindowY {
            get {
                return ResourceManager.GetString("WindowY", resourceCulture);
            }
        }
    }
}
