//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XEmuera.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigsText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigsText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XEmuera.Resources.ConfigsText", typeof(ConfigsText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自适应文字与图像.
        /// </summary>
        internal static string AdaptiveFont {
            get {
                return ResourceManager.GetString("AdaptiveFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自适应文字与图像大小.
        /// </summary>
        internal static string AdaptiveFontSize {
            get {
                return ResourceManager.GetString("AdaptiveFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 允许重写系统函数.
        /// </summary>
        internal static string AllowFunctionOverloading {
            get {
                return ResourceManager.GetString("AllowFunctionOverloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AllowLongInputByMouse {
            get {
                return ResourceManager.GetString("AllowLongInputByMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 允许多重启动.
        /// </summary>
        internal static string AllowMultipleInstances {
            get {
                return ResourceManager.GetString("AllowMultipleInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动保存进度.
        /// </summary>
        internal static string AutoSave {
            get {
                return ResourceManager.GetString("AutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 背景色.
        /// </summary>
        internal static string BackColor {
            get {
                return ResourceManager.GetString("BackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAR文字1.
        /// </summary>
        internal static string BarChar1 {
            get {
                return ResourceManager.GetString("BarChar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAR文字2.
        /// </summary>
        internal static string BarChar2 {
            get {
                return ResourceManager.GetString("BarChar2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不对按钮行折返换行.
        /// </summary>
        internal static string ButtonWrap {
            get {
                return ResourceManager.GetString("ButtonWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug模式下变更MASTER的称呼.
        /// </summary>
        internal static string ChangeMasterNameIfDebug {
            get {
                return ResourceManager.GetString("ChangeMasterNameIfDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM_ABLE初期値.
        /// </summary>
        internal static string ComAbleDefault {
            get {
                return ResourceManager.GetString("ComAbleDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 允许CALL调用事件函数.
        /// </summary>
        internal static string CompatiCallEvent {
            get {
                return ResourceManager.GetString("CompatiCallEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALLNAME为空时用NAME代替.
        /// </summary>
        internal static string CompatiCALLNAME {
            get {
                return ResourceManager.GetString("CompatiCALLNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRAWLINE始终打印在新行.
        /// </summary>
        internal static string CompatiDRAWLINE {
            get {
                return ResourceManager.GetString("CompatiDRAWLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 强制执行无法解析的行.
        /// </summary>
        internal static string CompatiErrorLine {
            get {
                return ResourceManager.GetString("CompatiErrorLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户函数自动补全TOSTR.
        /// </summary>
        internal static string CompatiFuncArgAutoConvert {
            get {
                return ResourceManager.GetString("CompatiFuncArgAutoConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户函数允许省略全部参数.
        /// </summary>
        internal static string CompatiFuncArgOptional {
            get {
                return ResourceManager.GetString("CompatiFuncArgOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 函数、属性的大小写敏感.
        /// </summary>
        internal static string CompatiFunctionNoignoreCase {
            get {
                return ResourceManager.GetString("CompatiFunctionNoignoreCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重现ver1739前的非按钮折返.
        /// </summary>
        internal static string CompatiLinefeedAs1739 {
            get {
                return ResourceManager.GetString("CompatiLinefeedAs1739", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用eramaker规范的伪变量RAND.
        /// </summary>
        internal static string CompatiRAND {
            get {
                return ResourceManager.GetString("CompatiRAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用SP角色.
        /// </summary>
        internal static string CompatiSPChara {
            get {
                return ResourceManager.GetString("CompatiSPChara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定调试窗口的位置.
        /// </summary>
        internal static string DebugSetWindowPos {
            get {
                return ResourceManager.GetString("DebugSetWindowPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动时显示调试窗口.
        /// </summary>
        internal static string DebugShowWindow {
            get {
                return ResourceManager.GetString("DebugShowWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调试窗口高度.
        /// </summary>
        internal static string DebugWindowHeight {
            get {
                return ResourceManager.GetString("DebugWindowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调试窗口X坐标.
        /// </summary>
        internal static string DebugWindowPosX {
            get {
                return ResourceManager.GetString("DebugWindowPosX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调试窗口Y坐标.
        /// </summary>
        internal static string DebugWindowPosY {
            get {
                return ResourceManager.GetString("DebugWindowPosY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动时窗口前置化显示.
        /// </summary>
        internal static string DebugWindowTopMost {
            get {
                return ResourceManager.GetString("DebugWindowTopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调试窗口宽度.
        /// </summary>
        internal static string DebugWindowWidth {
            get {
                return ResourceManager.GetString("DebugWindowWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载时显示报告.
        /// </summary>
        internal static string DisplayReport {
            get {
                return ResourceManager.GetString("DisplayReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最低显示警告等级.
        /// </summary>
        internal static string DisplayWarningLevel {
            get {
                return ResourceManager.GetString("DisplayWarningLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRAWLINE文字.
        /// </summary>
        internal static string DrawLineString {
            get {
                return ResourceManager.GetString("DrawLineString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑器运行参数.
        /// </summary>
        internal static string EditorArgument {
            get {
                return ResourceManager.GetString("EditorArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EditorType {
            get {
                return ResourceManager.GetString("EditorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用英语输出配置文件.
        /// </summary>
        internal static string EnglishConfigOutput {
            get {
                return ResourceManager.GetString("EnglishConfigOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPLVの初期値.
        /// </summary>
        internal static string ExpLvDef {
            get {
                return ResourceManager.GetString("ExpLvDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选中文字色.
        /// </summary>
        internal static string FocusColor {
            get {
                return ResourceManager.GetString("FocusColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字体名称.
        /// </summary>
        internal static string FontName {
            get {
                return ResourceManager.GetString("FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文字与图像缩放倍数.
        /// </summary>
        internal static string FontScale {
            get {
                return ResourceManager.GetString("FontScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字体大小.
        /// </summary>
        internal static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ForbidOneCodeVariable {
            get {
                return ResourceManager.GetString("ForbidOneCodeVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁用UPDATECHECK.
        /// </summary>
        internal static string ForbidUpdateCheck {
            get {
                return ResourceManager.GetString("ForbidUpdateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文字色.
        /// </summary>
        internal static string ForeColor {
            get {
                return ResourceManager.GetString("ForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每秒帧数.
        /// </summary>
        internal static string FPS {
            get {
                return ResourceManager.GetString("FPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 函数未被调用时的警告处理.
        /// </summary>
        internal static string FunctionNotCalledWarning {
            get {
                return ResourceManager.GetString("FunctionNotCalledWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 函数未找到时的警告处理.
        /// </summary>
        internal static string FunctionNotFoundWarning {
            get {
                return ResourceManager.GetString("FunctionNotFoundWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 忽视大小写.
        /// </summary>
        internal static string IgnoreCase {
            get {
                return ResourceManager.GetString("IgnoreCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 忽略未被调用过的函数.
        /// </summary>
        internal static string IgnoreUncalledFunction {
            get {
                return ResourceManager.GetString("IgnoreUncalledFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string IgnoreWarningFiles {
            get {
                return ResourceManager.GetString("IgnoreWarningFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 死循环超时警告（毫秒）.
        /// </summary>
        internal static string InfiniteLoopAlertTime {
            get {
                return ResourceManager.GetString("InfiniteLoopAlertTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最后更新口令.
        /// </summary>
        internal static string LastKey {
            get {
                return ResourceManager.GetString("LastKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每行高度.
        /// </summary>
        internal static string LineHeight {
            get {
                return ResourceManager.GetString("LineHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 起動時簡略表示.
        /// </summary>
        internal static string LoadLabel {
            get {
                return ResourceManager.GetString("LoadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 历史记录文字色.
        /// </summary>
        internal static string LogColor {
            get {
                return ResourceManager.GetString("LogColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 长按屏幕跳过文本.
        /// </summary>
        internal static string LongPressSkip {
            get {
                return ResourceManager.GetString("LongPressSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 长按所需毫秒数.
        /// </summary>
        internal static string LongPressSkipTime {
            get {
                return ResourceManager.GetString("LongPressSkipTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 记录日志的行数.
        /// </summary>
        internal static string MaxLog {
            get {
                return ResourceManager.GetString("MaxLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 販売アイテム数.
        /// </summary>
        internal static string MaxShopItem {
            get {
                return ResourceManager.GetString("MaxShopItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 単位の位置.
        /// </summary>
        internal static string MoneyFirst {
            get {
                return ResourceManager.GetString("MoneyFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to お金の単位.
        /// </summary>
        internal static string MoneyLabel {
            get {
                return ResourceManager.GetString("MoneyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PALAMLVの初期値.
        /// </summary>
        internal static string PalamLvDef {
            get {
                return ResourceManager.GetString("PalamLvDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 横向平移速度.
        /// </summary>
        internal static string PanSpeed {
            get {
                return ResourceManager.GetString("PanSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PBANDの初期値.
        /// </summary>
        internal static string pbandDef {
            get {
                return ResourceManager.GetString("pbandDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRINTC最大数量.
        /// </summary>
        internal static string PrintCLength {
            get {
                return ResourceManager.GetString("PrintCLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRINTC并列数量.
        /// </summary>
        internal static string PrintCPerLine {
            get {
                return ResourceManager.GetString("PrintCPerLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按钮显示列数.
        /// </summary>
        internal static string QuickButtonColumn {
            get {
                return ResourceManager.GetString("QuickButtonColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按钮字体大小.
        /// </summary>
        internal static string QuickButtonFontSize {
            get {
                return ResourceManager.GetString("QuickButtonFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按钮间隔.
        /// </summary>
        internal static string QuickButtonSpacing {
            get {
                return ResourceManager.GetString("QuickButtonSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按钮长度.
        /// </summary>
        internal static string QuickButtonWidth {
            get {
                return ResourceManager.GetString("QuickButtonWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载时解析参数.
        /// </summary>
        internal static string ReduceArgumentOnLoad {
            get {
                return ResourceManager.GetString("ReduceArgumentOnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ReduceFormattedStringOnLoad {
            get {
                return ResourceManager.GetString("ReduceFormattedStringOnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RELATIONの初期値.
        /// </summary>
        internal static string RelationDef {
            get {
                return ResourceManager.GetString("RelationDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用存档数量.
        /// </summary>
        internal static string SaveDataNos {
            get {
                return ResourceManager.GetString("SaveDataNos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 滚动行数.
        /// </summary>
        internal static string ScrollHeight {
            get {
                return ResourceManager.GetString("ScrollHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检索子目录.
        /// </summary>
        internal static string SearchSubdirectory {
            get {
                return ResourceManager.GetString("SearchSubdirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动时固定窗口位置.
        /// </summary>
        internal static string SetWindowPos {
            get {
                return ResourceManager.GetString("SetWindowPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图像抗锯齿.
        /// </summary>
        internal static string ShapeAntialias {
            get {
                return ResourceManager.GetString("ShapeAntialias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图像过滤质量.
        /// </summary>
        internal static string ShapeFilterQuality {
            get {
                return ResourceManager.GetString("ShapeFilterQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 允许调整窗口宽度.
        /// </summary>
        internal static string SizableWindow {
            get {
                return ResourceManager.GetString("SizableWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最大跳过帧数.
        /// </summary>
        internal static string SkipFrame {
            get {
                return ResourceManager.GetString("SkipFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按文件名顺序读取.
        /// </summary>
        internal static string SortWithFilename {
            get {
                return ResourceManager.GetString("SortWithFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 汚れの初期値.
        /// </summary>
        internal static string StainDefault {
            get {
                return ResourceManager.GetString("StainDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用全角空格填充空白区域.
        /// </summary>
        internal static string SystemAllowFullSpace {
            get {
                return ResourceManager.GetString("SystemAllowFullSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 强制将字符串变量的赋值转换为字符串.
        /// </summary>
        internal static string SystemIgnoreStringSet {
            get {
                return ResourceManager.GetString("SystemIgnoreStringSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 展开FORM中的三连记号.
        /// </summary>
        internal static string SystemIgnoreTripleSymbol {
            get {
                return ResourceManager.GetString("SystemIgnoreTripleSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁用角色变量的参数自动补全.
        /// </summary>
        internal static string SystemNoTarget {
            get {
                return ResourceManager.GetString("SystemNoTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将存档保存为二进制格式.
        /// </summary>
        internal static string SystemSaveInBinary {
            get {
                return ResourceManager.GetString("SystemSaveInBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 以UTF-8编码保存文件.
        /// </summary>
        internal static string SystemSaveInUTF8 {
            get {
                return ResourceManager.GetString("SystemSaveInUTF8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文字抗锯齿.
        /// </summary>
        internal static string TextAntialias {
            get {
                return ResourceManager.GetString("TextAntialias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 绘图接口.
        /// </summary>
        internal static string TextDrawingMode {
            get {
                return ResourceManager.GetString("TextDrawingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关联文本编辑器.
        /// </summary>
        internal static string TextEditor {
            get {
                return ResourceManager.GetString("TextEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文字过滤质量.
        /// </summary>
        internal static string TextFilterQuality {
            get {
                return ResourceManager.GetString("TextFilterQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用eramaker规范的TIMES计算.
        /// </summary>
        internal static string TimesNotRigorousCalculation {
            get {
                return ResourceManager.GetString("TimesNotRigorousCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 時間切れ表示.
        /// </summary>
        internal static string TimeupLabel {
            get {
                return ResourceManager.GetString("TimeupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to システムメニュー0.
        /// </summary>
        internal static string TitleMenuString0 {
            get {
                return ResourceManager.GetString("TitleMenuString0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to システムメニュー1.
        /// </summary>
        internal static string TitleMenuString1 {
            get {
                return ResourceManager.GetString("TitleMenuString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用调试指令.
        /// </summary>
        internal static string UseDebugCommand {
            get {
                return ResourceManager.GetString("UseDebugCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用ERD功能.
        /// </summary>
        internal static string UseERD {
            get {
                return ResourceManager.GetString("UseERD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用图像缓冲.
        /// </summary>
        internal static string UseImageBuffer {
            get {
                return ResourceManager.GetString("UseImageBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用键盘宏.
        /// </summary>
        internal static string UseKeyMacro {
            get {
                return ResourceManager.GetString("UseKeyMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内部使用的汉字编码.
        /// </summary>
        internal static string useLanguage {
            get {
                return ResourceManager.GetString("useLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示菜单栏.
        /// </summary>
        internal static string UseMenu {
            get {
                return ResourceManager.GetString("UseMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用鼠标.
        /// </summary>
        internal static string UseMouse {
            get {
                return ResourceManager.GetString("UseMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用_Rename.csv.
        /// </summary>
        internal static string UseRenameFile {
            get {
                return ResourceManager.GetString("UseRenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用_Replace.csv.
        /// </summary>
        internal static string UseReplaceFile {
            get {
                return ResourceManager.GetString("UseReplaceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在sav文件夹中创建存档.
        /// </summary>
        internal static string UseSaveFolder {
            get {
                return ResourceManager.GetString("UseSaveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 能够在LOADTEXT和SAVETEXT中使用的扩展名.
        /// </summary>
        internal static string ValidExtension {
            get {
                return ResourceManager.GetString("ValidExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VARSIZE使用与ERD相同的维度指定方式.
        /// </summary>
        internal static string VarsizeDimConfig {
            get {
                return ResourceManager.GetString("VarsizeDimConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示eramaker兼容性相关警告.
        /// </summary>
        internal static string WarnBackCompatibility {
            get {
                return ResourceManager.GetString("WarnBackCompatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重写系统函数时显示警告.
        /// </summary>
        internal static string WarnFunctionOverloading {
            get {
                return ResourceManager.GetString("WarnFunctionOverloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重复定义非事件函数时显示警告.
        /// </summary>
        internal static string WarnNormalFunctionOverloading {
            get {
                return ResourceManager.GetString("WarnNormalFunctionOverloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动时将窗口最大化.
        /// </summary>
        internal static string WindowMaximixed {
            get {
                return ResourceManager.GetString("WindowMaximixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 窗口X坐标.
        /// </summary>
        internal static string WindowPosX {
            get {
                return ResourceManager.GetString("WindowPosX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 窗口Y坐标.
        /// </summary>
        internal static string WindowPosY {
            get {
                return ResourceManager.GetString("WindowPosY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 窗口宽度.
        /// </summary>
        internal static string WindowX {
            get {
                return ResourceManager.GetString("WindowX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 窗口高度.
        /// </summary>
        internal static string WindowY {
            get {
                return ResourceManager.GetString("WindowY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将存档数据压缩保存.
        /// </summary>
        internal static string ZipSaveData {
            get {
                return ResourceManager.GetString("ZipSaveData", resourceCulture);
            }
        }
    }
}
