//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XEmuera.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringsText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsText() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XEmuera.Resources.StringsText", typeof(StringsText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 再按一次返回键退出应用。 的本地化字符串。
        /// </summary>
        internal static string BackButtonToQuit {
            get {
                return ResourceManager.GetString("BackButtonToQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码清单 的本地化字符串。
        /// </summary>
        internal static string CodeManifest {
            get {
                return ResourceManager.GetString("CodeManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 兼容性 的本地化字符串。
        /// </summary>
        internal static string Compati {
            get {
                return ResourceManager.GetString("Compati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏配置项 的本地化字符串。
        /// </summary>
        internal static string ConfigSettings {
            get {
                return ResourceManager.GetString("ConfigSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置值 的本地化字符串。
        /// </summary>
        internal static string ConfigValue {
            get {
                return ResourceManager.GetString("ConfigValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到csv文件夹 的本地化字符串。
        /// </summary>
        internal static string CSVFolderNotExists {
            get {
                return ResourceManager.GetString("CSVFolderNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调试 的本地化字符串。
        /// </summary>
        internal static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已禁用 的本地化字符串。
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文档 的本地化字符串。
        /// </summary>
        internal static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已启用 的本地化字符串。
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入配置值 的本地化字符串。
        /// </summary>
        internal static string EnterConfigValue {
            get {
                return ResourceManager.GetString("EnterConfigValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 环境 的本地化字符串。
        /// </summary>
        internal static string Environment {
            get {
                return ResourceManager.GetString("Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到erb文件夹 的本地化字符串。
        /// </summary>
        internal static string ERBFolderNotExists {
            get {
                return ResourceManager.GetString("ERBFolderNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文字 的本地化字符串。
        /// </summary>
        internal static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文字与图像 的本地化字符串。
        /// </summary>
        internal static string FontAndShape {
            get {
                return ResourceManager.GetString("FontAndShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅由游戏自行调用 的本地化字符串。
        /// </summary>
        internal static string FontOnlyCallInGame {
            get {
                return ResourceManager.GetString("FontOnlyCallInGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主动按顺序接替 的本地化字符串。
        /// </summary>
        internal static string FontReplaceByOrder {
            get {
                return ResourceManager.GetString("FontReplaceByOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体接替顺序 的本地化字符串。
        /// </summary>
        internal static string FontReplaceOrder {
            get {
                return ResourceManager.GetString("FontReplaceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请等待加载完成后再重启或退出游戏。 的本地化字符串。
        /// </summary>
        internal static string GameIsProcessing {
            get {
                return ResourceManager.GetString("GameIsProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏列表 的本地化字符串。
        /// </summary>
        internal static string GameList {
            get {
                return ResourceManager.GetString("GameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回标题界面 的本地化字符串。
        /// </summary>
        internal static string GotoTitle {
            get {
                return ResourceManager.GetString("GotoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要返回标题界面吗 的本地化字符串。
        /// </summary>
        internal static string GotoTitleConfirm {
            get {
                return ResourceManager.GetString("GotoTitleConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已成功将语言设置为 {0}，是否立即重新启动软件？ 的本地化字符串。
        /// </summary>
        internal static string LanguageChangedNeedReboot {
            get {
                return ResourceManager.GetString("LanguageChangedNeedReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前平台需要授予文件管理权限，即将为您跳转至权限管理界面。 的本地化字符串。
        /// </summary>
        internal static string NeedManageFilesPermissions {
            get {
                return ResourceManager.GetString("NeedManageFilesPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无文件夹 的本地化字符串。
        /// </summary>
        internal static string NoFolder {
            get {
                return ResourceManager.GetString("NoFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开源代码使用清单 的本地化字符串。
        /// </summary>
        internal static string OpenSourceCodeManifest {
            get {
                return ResourceManager.GetString("OpenSourceCodeManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他配置项 的本地化字符串。
        /// </summary>
        internal static string OtherConfigSettings {
            get {
                return ResourceManager.GetString("OtherConfigSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 覆写游戏原配置 的本地化字符串。
        /// </summary>
        internal static string OverwriteGameConfig {
            get {
                return ResourceManager.GetString("OverwriteGameConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限获取失败，请重新启动软件或手动授予权限。 的本地化字符串。
        /// </summary>
        internal static string PermissionsRequestFailed {
            get {
                return ResourceManager.GetString("PermissionsRequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目地址 的本地化字符串。
        /// </summary>
        internal static string ProjectWebSite {
            get {
                return ResourceManager.GetString("ProjectWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快捷按钮 的本地化字符串。
        /// </summary>
        internal static string QuickButton {
            get {
                return ResourceManager.GetString("QuickButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要退出游戏吗？ 的本地化字符串。
        /// </summary>
        internal static string QuitGameConfirm {
            get {
                return ResourceManager.GetString("QuitGameConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新加载 的本地化字符串。
        /// </summary>
        internal static string Reboot {
            get {
                return ResourceManager.GetString("Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要重新加载吗 的本地化字符串。
        /// </summary>
        internal static string RebootConfirm {
            get {
                return ResourceManager.GetString("RebootConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件使用声明 的本地化字符串。
        /// </summary>
        internal static string SoftwareUsageStatement {
            get {
                return ResourceManager.GetString("SoftwareUsageStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本软件遵循MIT开源许可协议，免费使用软件和开放源码。
        ///本软件的项目地址即为唯一指定下载地址，请确保您的软件获取自官方。
        ///对于用户使用本软件造成的任何损失，作者概不负责。 的本地化字符串。
        /// </summary>
        internal static string SoftwareUsageStatementDetail {
            get {
                return ResourceManager.GetString("SoftwareUsageStatementDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 支持作者 的本地化字符串。
        /// </summary>
        internal static string SupportMe {
            get {
                return ResourceManager.GetString("SupportMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统 的本地化字符串。
        /// </summary>
        internal static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统2 的本地化字符串。
        /// </summary>
        internal static string System2 {
            get {
                return ResourceManager.GetString("System2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用游戏原配置 的本地化字符串。
        /// </summary>
        internal static string UseGameConfig {
            get {
                return ResourceManager.GetString("UseGameConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本 的本地化字符串。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示 的本地化字符串。
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口 的本地化字符串。
        /// </summary>
        internal static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
    }
}
